version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/install-packages:
          pkg-manager: pip
          include-python-in-cache-key: false
      - run: pip install --ignore-installed coverage
      - run: ./manage.py collectstatic
      - run: ~/.local/bin/coverage run --source='.' manage.py test
      #- run:
         # command: ./manage.py test
          #name: Test
      #- run: ./manage.py collectstatic
      #- run: ~/.local/bin/coverage run --source='.' manage.py test

workflows:
  main:
    jobs:
      - build-and-test
