version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.2.3

jobs:
  build-and-test:
    executor: python/default
    #docker:
     # -image: circleci/python:3.8
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      #- run:
         # command: ./manage.py test
          #name: Test
      #- run: ./manage.py collectstatic
      #- run: ~/.local/bin/coverage run --source='.' manage.py test

workflows:
  master:
    jobs:
      - build-and-test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build-and-test
          filters:
            branches:
              only: master
